//! License token format + Ed25519 verification.
//!
//! Wire format is JSON with these fields:
//! ```json
//! {
//!   "v": 1,
//!   "key": "DM-XXXX-XXXX-XXXX-XXXX-XXXX",
//!   "plan": "lifetime" | "trial",
//!   "fingerprint": "<sha256_hex_32>",
//!   "issued_at": "<RFC3339>",
//!   "expires_at": "<RFC3339>" | null,
//!   "sig": "<base64_ed25519_signature>"
//! }
//! ```
//!
//! The signature is over the JSON-canonical form of the same struct **with
//! `sig` removed**. The server signs with its private key, the client
//! verifies with the bundled [`SERVER_PUBLIC_KEY`].

use chrono::{DateTime, Utc};
use ed25519_dalek::{Signature, Verifier, VerifyingKey, SIGNATURE_LENGTH};
use serde::{Deserialize, Serialize};

/// Hex-encoded Ed25519 public key of the license server.
/// Generated by `docmind-server` on first start and persisted to
/// `data/keys/ed25519.pub` on the operator's server. Update this constant
/// (and rebuild the client) whenever the server-side keypair is rotated.
pub const SERVER_PUBLIC_KEY_HEX: &str =
    "0af65e2ccf560c2f4f009fc5b30acb4c1fb011dc367b04c38e7f0c3a3f3ef926";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum TokenPlan {
    Lifetime,
    Trial,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LicenseToken {
    pub v: u32,
    pub key: String,
    pub plan: TokenPlan,
    pub fingerprint: String,
    pub issued_at: DateTime<Utc>,
    #[serde(default)]
    pub expires_at: Option<DateTime<Utc>>,
    pub sig: String,
}

#[derive(Debug)]
pub enum TokenError {
    Malformed(serde_json::Error),
    PublicKeyMissing,
    BadSignature,
    Hex(hex::FromHexError),
    Base64,
    UnsupportedVersion(u32),
}

impl std::fmt::Display for TokenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TokenError::Malformed(e) => write!(f, "token JSON malformed: {e}"),
            TokenError::PublicKeyMissing => write!(f, "server public key is not configured"),
            TokenError::BadSignature => write!(f, "signature is invalid"),
            TokenError::Hex(e) => write!(f, "hex decode failed: {e}"),
            TokenError::Base64 => write!(f, "base64 decode failed"),
            TokenError::UnsupportedVersion(v) => write!(f, "token version {v} is not supported"),
        }
    }
}

impl std::error::Error for TokenError {}

impl From<serde_json::Error> for TokenError {
    fn from(e: serde_json::Error) -> Self {
        TokenError::Malformed(e)
    }
}

impl From<hex::FromHexError> for TokenError {
    fn from(e: hex::FromHexError) -> Self {
        TokenError::Hex(e)
    }
}

impl LicenseToken {
    /// Parses a JSON string and verifies the signature.
    pub fn parse_and_verify(json: &str) -> Result<Self, TokenError> {
        let token: LicenseToken = serde_json::from_str(json)?;
        if token.v != 1 {
            return Err(TokenError::UnsupportedVersion(token.v));
        }
        token.verify_signature()?;
        Ok(token)
    }

    fn verify_signature(&self) -> Result<(), TokenError> {
        let key_bytes = hex::decode(SERVER_PUBLIC_KEY_HEX)?;
        if key_bytes == vec![0u8; 32] {
            return Err(TokenError::PublicKeyMissing);
        }
        let key_array: [u8; 32] = key_bytes
            .as_slice()
            .try_into()
            .map_err(|_| TokenError::PublicKeyMissing)?;
        let verifying =
            VerifyingKey::from_bytes(&key_array).map_err(|_| TokenError::PublicKeyMissing)?;

        let sig_bytes = base64_decode(&self.sig).ok_or(TokenError::Base64)?;
        if sig_bytes.len() != SIGNATURE_LENGTH {
            return Err(TokenError::BadSignature);
        }
        let mut sig_arr = [0u8; SIGNATURE_LENGTH];
        sig_arr.copy_from_slice(&sig_bytes);
        let signature = Signature::from_bytes(&sig_arr);

        let payload = self.canonical_payload();
        verifying
            .verify(payload.as_bytes(), &signature)
            .map_err(|_| TokenError::BadSignature)
    }

    /// Canonical signing payload — stable JSON serialization with `sig` cleared.
    /// The server must produce the **exact** same bytes when signing.
    pub fn canonical_payload(&self) -> String {
        let mut copy = self.clone();
        copy.sig = String::new();
        serde_json::to_string(&copy).unwrap_or_default()
    }

    pub fn is_expired(&self) -> bool {
        self.expires_at
            .map(|exp| exp < Utc::now())
            .unwrap_or(false)
    }

    pub fn fingerprint_matches(&self, current: &str) -> bool {
        self.fingerprint.eq_ignore_ascii_case(current)
    }
}

fn base64_decode(s: &str) -> Option<Vec<u8>> {
    use base64::{engine::general_purpose::STANDARD, Engine as _};
    STANDARD.decode(s.trim()).ok()
}
